version: '2.1'

services:
  database:
    image: mongo
    container_name: 'database'
    restart: always
    volumes:
      - ~/docker/mongo/data/db:/data/db
    networks:
      - webapp-network
  egg-api:
    # image: egg-api
    container_name: 'egg-api'
    image: registry.cn-hangzhou.aliyuncs.com/yangpu/egg-web:1.0.0
    depends_on:
      - database
    # build: .
    environment:
      NODE_ENV: production
    ports:
      - 3330:3330
    networks:
      - webapp-network
  nginx_web:
    image: nginx
    ports:
      - 80:80
    container_name: 'nginx_web'
    restart: always
    networks:
      - webapp-network
    volumes:
      # - ~/docker/nginx/html:/usr/share/nginx/html/:ro
      - ~/docker/nginx/html:/usr/share/nginx/html
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx.conf:/etc/nginx/nginx.conf
networks:
  webapp-network:
    driver: bridge