version: '2.1'

services:
  database:
    image: mongo
    restart: always
    volumes:
      - ~/docker/mongo/data/db:/data/db
    networks:
      - webapp-network
  egg-api:
    image: egg-api
    depends_on:
      - database
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3330:3330
    networks:
      - webapp-network
  nginx_web:
    image: nginx
    ports:
      - 80:80
    container_name: 'nginx_web'
    restart: always
    networks:
      - webapp-network
    volumes:
      # - ~/docker/nginx/html:/usr/share/nginx/html/:ro
      - ~/docker/nginx/html:/usr/share/nginx/html
      # - ./nginx.conf:/etc/nginx/nginx.conf
networks:
  webapp-network:
    driver: bridge